name: CI

on:
  push:
    branches:
      - master
      - main
      - "v*"
    tags:
      - "v*"
  pull_request:

jobs:
  tests:
    name: "Tests on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20", "22", "24"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
